### ISSUE TITLE
Authentication question

### ISSUE THREAD

**Issue by jordansissel** [libgit2/rugged#422]
Howdy!

I am attempting to use Rugged to push some git changes, but when I push with a https remote, I get: `authentication required but no callback set`. If I attempt with an ssh git url `git@github.com:/whatever/blah.git` or `ssh://...` the error is `Rugged::NetworkError: This transport isn't implemented. Sorry`

Not super sure what  to do. I wasn't able to find anything about an authentication callback in the rugged docs. WIthout ssh support or a way to pass credentials to https, I'm not sure how to proceed.

Help? :)

**Comment by mattmeng** [comment]
I'm having almost the same issue, but I've compiled libgit2 with with ssh support (I believe):

```
$ ldd /usr/local/lib/libgit2.so
	linux-vdso.so.1 =>  (0x00007fffeafa2000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f2d7354d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2d73334000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2d730d4000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2d72cf9000)
	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f2d72ad1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2d728c8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d726aa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d722e5000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f2d720b1000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f2d71e97000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2d71c51000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f2d71a41000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f2d717f0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2d715ec000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f2d7136b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2d73aed000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f2d710ad000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2d70de1000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f2d70bb2000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f2d709ae000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f2d707a2000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f2d70587000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f2d7036c000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f2d7012d000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2d6ff28000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f2d6fd14000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f2d6fad1000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f2d6f8cd000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f2d6f6c3000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f2d6f43b000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f2d6f19a000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f2d6ef66000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f2d6ed51000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f2d6eb49000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f2d6e91f000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f2d6e711000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f2d6e4c8000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f2d6e20e000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f2d6dfd5000)
```

I've tried installing Rugged with and without `--use-system-libraries`, but I get the same errors:

```
authentication required but no callback set
  "/usr/local/lib/ruby/gems/2.2.0/gems/rugged-0.23.2/lib/rugged/repository.rb:224:in `push'"
  "/usr/local/lib/ruby/gems/2.2.0/gems/rugged-0.23.2/lib/rugged/repository.rb:224:in `push'"
  "./script.rb:48:in `<main>'"
```

I don't, however, get @jordansissel's `Rugged::NetworkError: This transport isn't implemented. Sorry`.

Code used:

```ruby
repo = Rugged::Repository.new( repo_name )
repo.push( remote_name, branch_name )
```

**Comment by arthurschreiber** [comment]
I'm not at my computer right now, but from the code snippet and error message you posted, it looks like you're not providing any credentials object on the call to 'push'.

**Comment by mattmeng** [comment]
I think your right.  I was not aware of the credentials key I needed to pass.  Thanks for your help.  Is there a good tutorial on how to use Rugged?  I'd like to really get into it, but I'm having trouble getting up to speed.  Google returns very little info.

**Comment by jtoy** [comment]
i just got the same error, i think its something else that is causing it though. I reissued new read keys and now no matter what I do i cant get the system to clone

I call it like so:
url ="https://xx95f82@github.com/org/blah.git"
 r=Rugged::Repository.clone_at url,dir

!! #<Rugged::NetworkError: authentication required but no callback set>
