### ISSUE TITLE
Rugged 0.23.0 Makefile error

### ISSUE THREAD

**Issue by dankohn** [libgit2/rugged#504]
In order to deal with the rugged dld error https://github.com/libgit2/rugged/issues/475 I changed pronto to require rugged 0.23.0, but using `gem 'rugged', github: 'libgit2/rugged', ref: '233da19'` in my Gemfile produces:
```bash
Using rugged 0.23.0 (was 0.22.2) from git://github.com/libgit2/rugged.git (at 233da19)

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/dan/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150720-36471-ccu0y8.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/dan/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
	from extconf.rb:66:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rugged-233da19f4821 for inspection.
Results logged to /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/extensions/x86_64-darwin-14/2.2.0-static/rugged-233da19f4821/gem_make.out
An error occurred while installing rugged (0.23.0), and Bundler cannot continue.
```
I also tried:
```bash
$ gem install rugged  --pre
Fetching: rugged-0.23.0b4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
	ERROR: Failed to build gem native extension.

    /Users/dan/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150720-36618-1mmje1s.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/dan/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
	from extconf.rb:66:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rugged-0.23.0b4 for inspection.
Results logged to /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/rugged-0.23.0b4/gem_make.out
```
As suggested in https://github.com/libgit2/rugged/issues/489 I installed XCode (as opposed to the XCode Command Line Tools I had previously been using) and entered `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` but this didn't change the error.

I'm on Yosemite 10.10.4.

**Comment by arthurschreiber** [comment]
Can you also create a gist with the content of `mkmf.log` and link it here?

**Comment by dankohn** [comment]
I was getting an error because I needed to authorize the license for XCode. `gem install rugged  --pre` now works. Using gem 'rugged', github: 'libgit2/rugged', ref: '233da19' in my Gemfile still produces the same error:

less /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/extensions/x86_64-darwin-14/2.2.0-static/rugged-233da19f4821/mkmf.log
```
find_executable: checking for gmake... -------------------- no

--------------------

find_executable: checking for make... -------------------- yes

--------------------

find_executable: checking for cmake... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

"cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles""
CMake Error: The source directory "/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rugged-233da19f4821/vendor/libgit2" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by arthurschreiber** [comment]
You need to tell bundler to include git submodules. This is mentioned in the Readme.

This will work:

```
gem 'rugged', github: 'libgit2/rugged', ref: '233da19', submodules: true
```

**Comment by dankohn** [comment]
Will do, thanks very much for the quick correction. 

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000
