### ISSUE TITLE
truffleruby: Could not find a search path for git2 -- passing libgit2.dylib on to Sulong

### ISSUE THREAD

**Issue by bbuchalter** [libgit2/rugged#822]
```
$ ruby -v
truffleruby 19.2.0.1, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]

$ cat Gemfile
source 'https://rubygems.org'
gem 'rugged', git: 'git://github.com/libgit2/rugged.git', submodules: true


$ bundle -v
Bundler version 1.17.2


$ bundle install
The git source `git://github.com/libgit2/rugged.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/libgit2/rugged.git
Submodule 'vendor/libgit2' (https://github.com/libgit2/libgit2.git) registered for path 'vendor/libgit2'
Cloning into '/Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270/vendor/libgit2'...
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.17.2
Using rugged 0.28.0 from git://github.com/libgit2/rugged.git (at master@3de6a0a)

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270/ext/rugged
/Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/bin/truffleruby -I /Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/lib/mri -r ./siteconf20191102-15594-1wypjk4.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Success
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Success
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED - Success
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED - Success
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED - Success
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED - Success
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED - Success
-- Performing Test IS_WINT_CONVERSION_SUPPORTED
-- Performing Test IS_WINT_CONVERSION_SUPPORTED - Success
-- Performing Test IS_WFORMAT_SUPPORTED
-- Performing Test IS_WFORMAT_SUPPORTED - Success
-- Performing Test IS_WFORMAT_SECURITY_SUPPORTED
-- Performing Test IS_WFORMAT_SECURITY_SUPPORTED - Success
-- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED
-- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED - Success
-- Looking for futimens
-- Looking for futimens - found
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - True
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - False
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
-- Found Security /System/Library/Frameworks/Security.framework
-- Looking for SSLCreateContext in /System/Library/Frameworks/Security.framework
-- Looking for SSLCreateContext in /System/Library/Frameworks/Security.framework - found
-- Found CoreFoundation /System/Library/Frameworks/CoreFoundation.framework
ON
-- Found PCRE: /usr/local/lib/libpcre.dylib
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoq
-- Looking for strtoq - found
-- Looking for _strtoi64
-- Looking for _strtoi64 - not found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED - Success
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED - Success
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED - Failed
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- Checking for module 'libssh2'
--   No package 'libssh2' found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Found Iconv: -L/usr/lib -liconv
-- Enabled features:
 * nanoseconds, whether to use sub-second file mtimes and ctimes
 * threadsafe, threadsafe support
 * HTTPS, using SecureTransport
 * SHA, using CollisionDetection
 * regex, using bundled PCRE
 * http-parser, http-parser support (bundled)
 * zlib, using system zlib
 * ntlmclient, NTLM authentication support for Unix
 * iconv, iconv encoding conversion support

-- Disabled features:
 * debugpool, debug pool allocator
 * tracing, tracing support
 * SSH, SSH transport support
 * SPNEGO, SPNEGO authentication support

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270/vendor/libgit2/build
 -- /usr/bin/make
checking for -lgit2... yes
checking for git2.h... yes
creating Makefile

current directory: /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270/ext/rugged
make "DESTDIR=" clean

current directory: /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270/ext/rugged
make "DESTDIR="
compiling rugged.c
compiling rugged_allocator.c
compiling rugged_backend.c
compiling rugged_blame.c
compiling rugged_blob.c
compiling rugged_branch.c
compiling rugged_branch_collection.c
compiling rugged_commit.c
compiling rugged_config.c
compiling rugged_cred.c
compiling rugged_diff.c
compiling rugged_diff_delta.c
compiling rugged_diff_hunk.c
compiling rugged_diff_line.c
compiling rugged_index.c
compiling rugged_note.c
compiling rugged_object.c
compiling rugged_patch.c
compiling rugged_rebase.c
compiling rugged_reference.c
compiling rugged_reference_collection.c
compiling rugged_remote.c
compiling rugged_remote_collection.c
compiling rugged_repo.c
compiling rugged_revwalk.c
compiling rugged_settings.c
compiling rugged_signature.c
compiling rugged_submodule.c
compiling rugged_submodule_collection.c
compiling rugged_tag.c
compiling rugged_tag_collection.c
compiling rugged_tree.c
linking shared-object rugged/rugged.su
Could not find a search path for git2 -- passing libgit2.dylib on to Sulong
/Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/lib/cext/linker.rb:67:in `process_args': Unknown argument: -framework (RuntimeError)
	from /Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/lib/cext/linker.rb:21:in `main'
	from /Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/lib/cext/linker.rb:150:in `<main>'
make: *** [rugged.su] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/rugged-3de6a0a76270 for inspection.
Results logged to /Users/brian.buchalter/.gem/truffleruby/2.6.2/bundler/gems/extensions/x86_64-darwin/19.2.0.1/rugged-3de6a0a76270/gem_make.out

An error occurred while installing rugged (0.28.0), and Bundler cannot continue.

In Gemfile:
  rugged
```

**Comment by bbuchalter** [comment]
```
linking shared-object rugged/rugged.su
Could not find a search path for git2 -- passing libgit2.dylib on to Sulong
/Users/brian.buchalter/.rubies/truffleruby-19.2.0.1/lib/cext/linker.rb:67:in `process_args': Unknown argument: -framework (RuntimeError)
```

seem to be the highlights...any ideas? do I need to post this elsewhere? This was just an experiment.

cc: @cbrunsdon
